FROM golang:1.19

RUN GO111MODULE=on go get github.com/GoogleContainerTools/container-structure-test/cmd/container-structure-test/ github.com/mikefarah/yq/v3

COPY Dockerfile_test.yml ./

ARG GREENPLUM_VERSION
ARG MADLIB_VERSION
ARG PXF_VERSION
ARG GPBACKUP_VERSION

RUN	yq w -i ./Dockerfile_test.yml "metadataTest.labels(key == greenplum_version).value" "${GREENPLUM_VERSION}" && \
	yq w -i ./Dockerfile_test.yml "metadataTest.labels(key == madlib_version).value" "${MADLIB_VERSION}" && \
	yq w -i ./Dockerfile_test.yml "metadataTest.labels(key == pxf_version).value" "${PXF_VERSION}" && \
	yq w -i ./Dockerfile_test.yml "metadataTest.labels(key == gpbackup_version).value" "${GPBACKUP_VERSION}" && \

ARG IMAGE_TAG
ENV IMAGE_TAG=${IMAGE_TAG}

CMD	container-structure-test test --image ${IMAGE_TAG} --config ./Dockerfile_test.yml
