// +build !ignore_autogenerated

/*
.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenplumCluster) DeepCopyInto(out *GreenplumCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenplumCluster.
func (in *GreenplumCluster) DeepCopy() *GreenplumCluster {
	if in == nil {
		return nil
	}
	out := new(GreenplumCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GreenplumCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenplumClusterList) DeepCopyInto(out *GreenplumClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GreenplumCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenplumClusterList.
func (in *GreenplumClusterList) DeepCopy() *GreenplumClusterList {
	if in == nil {
		return nil
	}
	out := new(GreenplumClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GreenplumClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenplumClusterSpec) DeepCopyInto(out *GreenplumClusterSpec) {
	*out = *in
	in.MasterAndStandby.DeepCopyInto(&out.MasterAndStandby)
	in.Segments.DeepCopyInto(&out.Segments)
	out.PXF = in.PXF
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenplumClusterSpec.
func (in *GreenplumClusterSpec) DeepCopy() *GreenplumClusterSpec {
	if in == nil {
		return nil
	}
	out := new(GreenplumClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenplumClusterStatus) DeepCopyInto(out *GreenplumClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenplumClusterStatus.
func (in *GreenplumClusterStatus) DeepCopy() *GreenplumClusterStatus {
	if in == nil {
		return nil
	}
	out := new(GreenplumClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenplumMasterAndStandbySpec) DeepCopyInto(out *GreenplumMasterAndStandbySpec) {
	*out = *in
	in.GreenplumPodSpec.DeepCopyInto(&out.GreenplumPodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenplumMasterAndStandbySpec.
func (in *GreenplumMasterAndStandbySpec) DeepCopy() *GreenplumMasterAndStandbySpec {
	if in == nil {
		return nil
	}
	out := new(GreenplumMasterAndStandbySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenplumPXFSpec) DeepCopyInto(out *GreenplumPXFSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenplumPXFSpec.
func (in *GreenplumPXFSpec) DeepCopy() *GreenplumPXFSpec {
	if in == nil {
		return nil
	}
	out := new(GreenplumPXFSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenplumPodSpec) DeepCopyInto(out *GreenplumPodSpec) {
	*out = *in
	out.Memory = in.Memory.DeepCopy()
	out.CPU = in.CPU.DeepCopy()
	out.Storage = in.Storage.DeepCopy()
	if in.WorkerSelector != nil {
		in, out := &in.WorkerSelector, &out.WorkerSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenplumPodSpec.
func (in *GreenplumPodSpec) DeepCopy() *GreenplumPodSpec {
	if in == nil {
		return nil
	}
	out := new(GreenplumPodSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenplumSegmentsSpec) DeepCopyInto(out *GreenplumSegmentsSpec) {
	*out = *in
	in.GreenplumPodSpec.DeepCopyInto(&out.GreenplumPodSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenplumSegmentsSpec.
func (in *GreenplumSegmentsSpec) DeepCopy() *GreenplumSegmentsSpec {
	if in == nil {
		return nil
	}
	out := new(GreenplumSegmentsSpec)
	in.DeepCopyInto(out)
	return out
}
