FROM golang:1.19

RUN GO111MODULE=on go get github.com/GoogleContainerTools/container-structure-test/cmd/container-structure-test/ github.com/mikefarah/yq/v3

COPY ./greenplum-instance/Dockerfile_test.yml ./

ARG VERSION
ARG DATE
ARG GREENPLUM_VERSION

RUN \
    # Disable the GREENPLUM_VERSION check if GREENPLUM_VERSION = latest
    if [ "${GREENPLUM_VERSION}" = "latest" ] ; then \
        yq d -i ./Dockerfile_test.yml "metadataTest.env(key == GREENPLUM_VERSION)" ; \
    else \
	    yq w -i ./Dockerfile_test.yml "metadataTest.env(key == GREENPLUM_VERSION).value" "${GREENPLUM_VERSION}" ; \
    fi && \
    yq w -i ./Dockerfile_test.yml "metadataTest.labels(key == version).value" "${VERSION}" && \
	yq w -i ./Dockerfile_test.yml "metadataTest.labels(key == build_date).value" "${DATE}"

ARG IMAGE_TAG
ENV IMAGE_TAG=${IMAGE_TAG}

CMD	container-structure-test test --image ${IMAGE_TAG} --config ./Dockerfile_test.yml
