// +build !ignore_autogenerated

/*
.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenplumPXFConf) DeepCopyInto(out *GreenplumPXFConf) {
	*out = *in
	out.S3Source = in.S3Source
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenplumPXFConf.
func (in *GreenplumPXFConf) DeepCopy() *GreenplumPXFConf {
	if in == nil {
		return nil
	}
	out := new(GreenplumPXFConf)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenplumPXFService) DeepCopyInto(out *GreenplumPXFService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenplumPXFService.
func (in *GreenplumPXFService) DeepCopy() *GreenplumPXFService {
	if in == nil {
		return nil
	}
	out := new(GreenplumPXFService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GreenplumPXFService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenplumPXFServiceList) DeepCopyInto(out *GreenplumPXFServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GreenplumPXFService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenplumPXFServiceList.
func (in *GreenplumPXFServiceList) DeepCopy() *GreenplumPXFServiceList {
	if in == nil {
		return nil
	}
	out := new(GreenplumPXFServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GreenplumPXFServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenplumPXFServiceSpec) DeepCopyInto(out *GreenplumPXFServiceSpec) {
	*out = *in
	out.CPU = in.CPU.DeepCopy()
	out.Memory = in.Memory.DeepCopy()
	if in.WorkerSelector != nil {
		in, out := &in.WorkerSelector, &out.WorkerSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PXFConf != nil {
		in, out := &in.PXFConf, &out.PXFConf
		*out = new(GreenplumPXFConf)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenplumPXFServiceSpec.
func (in *GreenplumPXFServiceSpec) DeepCopy() *GreenplumPXFServiceSpec {
	if in == nil {
		return nil
	}
	out := new(GreenplumPXFServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GreenplumPXFServiceStatus) DeepCopyInto(out *GreenplumPXFServiceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GreenplumPXFServiceStatus.
func (in *GreenplumPXFServiceStatus) DeepCopy() *GreenplumPXFServiceStatus {
	if in == nil {
		return nil
	}
	out := new(GreenplumPXFServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Source) DeepCopyInto(out *S3Source) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Source.
func (in *S3Source) DeepCopy() *S3Source {
	if in == nil {
		return nil
	}
	out := new(S3Source)
	in.DeepCopyInto(out)
	return out
}
