apiVersion: "greenplum.pivotal.io/v1"
kind: "GreenplumCluster"
metadata:
  name: my-greenplum
spec:
  loadBalancer: yes
  masterAndStandby:
    hostBasedAuthentication: |
      # host   all   gpadmin   0.0.0.0/0   trust
    memory: "800Mi"
    cpu: "0.5"
    persistentVolumeClaims:
      - name: pgdata
        storageClassName: standard
        storage: 1G
        mountPath: /greenplum
    workerSelector: {}
  segments:
    primarySegmentCount: 1
    memory: "800Mi"
    cpu: "0.5"
    persistentVolumeClaims:
      - name: pgdata
        storageClassName: standard
        storage: 2G
        mountPath: /greenplum
    workerSelector: {}
